[package]
name = "netcdf"
version = "0.3.2"
authors = [
    "Michael Hiley <mike.hiley@ssec.wisc.edu>",
    "Magnus Ulimoen <magnusu@met.no>"
]
license = "MIT OR Apache-2.0"
description = "High-level NetCDF bindings for Rust"
repository = "https://github.com/mhiley/rust-netcdf"
documentation = "https://github.com/mhiley/rust-netcdf"
keywords = ["netcdf", "hdf", "hdf5", "libnetcdf", "netcdf4"]
edition = "2018"

[features]
default = ["ndarray", "indexmap"]
memory = ["netcdf-sys/memio"]

[dependencies]
lazy_static = "1.4.0"
ndarray = { version = "0.12.*", optional = true }
indexmap = { version = "1.2.*", optional = true }

[dev-dependencies]
tempfile = "3.1.0"

[dependencies.netcdf-sys]
path = "netcdf-sys"
