[package]
name = "netcdf-sys"
version = "0.2.0"
authors = ["Mike Hiley <mike.hiley@ssec.wisc.edu>"]
license = "MIT"
description = "FFI bindings to NetCDF"
repository = "https://github.com/mhiley/rust-netcdf"
documentation = "https://github.com/mhiley/rust-netcdf"
keywords = ["netcdf", "hdf", "hdf4", "hdf5", "cdm"]

[dependencies]
libc = "0.2"
lazy_static = "1.0"
