[package]
name = "netcdf-sys"
version = "0.1.0"
authors = ["Mike Hiley <mike.hiley@ssec.wisc.edu>"]
license = "MIT"
description = "FFI bindings to NetCDF"
repository = "https://github.com/mhiley/rust-netcdf"
documentation = "https://github.com/mhiley/rust-netcdf"
keywords = ["netcdf", "hdf", "hdf4", "hdf5", "cdm"]

links = "netcdf"
build = "build.rs"

[build-dependencies]
gcc = "0.3.8"

[dependencies]
libc = "0.1.8"
lazy_static = "0.1.11"
