[package]
name = "netcdf-sys"
version = "0.2.0"
authors = [
    "Michael Hiley <mhiley@gmail.com>",
    "Magnus Ulimoen <magnusu@met.no>"
]
license = "MIT"
description = "FFI bindings to NetCDF"
repository = "https://github.com/mhiley/rust-netcdf"
documentation = "https://github.com/mhiley/rust-netcdf"
keywords = ["netcdf", "hdf", "hdf4", "hdf5", "cdm", "ffi"]
edition = "2018"
links = "netcdf"
build = "build.rs"

[dev-dependencies]
lazy_static = "1.4.0"

[features]
memio = []
