name: codecov
on: [push]
env:
  CARGO_TERM_COLOR: always

jobs:
  tarpaulin:
    name: tarpaulin
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install netcdf
      run: sudo apt-get install libnetcdf-dev

    - name: Install rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install tarpaulin
      uses: baptiste0928/cargo-install@v2.1.0
      with:
        crate: cargo-tarpaulin
        version: "0.26.0"

    - name: Tarpaulin
      run: cargo tarpaulin --verbose --out Xml --ignore-tests

    - name: Upload to codecov
      uses: codecov/codecov-action@v3.1.4
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
